### ISSUE TITLE
Greyscale Stuck

### ISSUE THREAD

**Issue by bdmiller42** [GrapheneOS/os_issue_tracker#6001]
Turning on greyscale or other color correction in accessability makes color correction untoggleable. Have to restart device to get colors back.

**Comment by BWotka** [comment]
Same on P7A, Version 2025112100

The workaround still works.

I believe this also caused a crash of the OS when switching to a different profile, but was not able to reproduce.

**Comment by Epilogue3859** [comment]
Confirming this still occurs on GrapheneOS with Android 16.

Device: Pixel 6a  
GrapheneOS build: 2026011001  
Android version: 16  
Security patch: January 5, 2026  

Behavior:
- Enable Color correction (e.g. Grayscale)
- Disable Color correction
- UI toggle switches off, but display remains color-corrected
- A full reboot restores normal colors

After disabling Color correction, the display remains color-corrected.
A full reboot reliably restores normal colors.

As a workaround, toggling Night Light on and off after disabling Color correction also resets the display and restores normal colors.

**Comment by velvetorange128** [comment]
I have the same issue

Device: Pixel 7
GrapheneOS build: 2026011301
Android version: 16
Security patch: January 5, 2026

Workaround still works, but I only learned of it via this issue

**Comment by Neo-Ston** [comment]
Device: pixel 7 Pro
GrapheneOS build: 2026012800
Android Version: 16
I have the same issue as mentioned, only found the workaround due to this issue however nightlight change does not seem to work for me, only a restart does.

Correction: night light change does work if I toggle the grayscale color correction after I turn on the night light.

**Comment by marioscgeorgiou** [comment]
I have the same issue, only (unreliable) fix is restarting the phone. Gets stuck both with system settings greyscale and apps that control greyscale e.g. Gray-switch

Device: Pixel 9 Pro
GrapheneOS build: 2026062801
Android v17

**Comment by paotsaq** [comment]
I also have this bug, and I have had it for many months. 

I prefer to run grayscale mode all the time, and I first noticed an issue when I tried to use the accessibility home screen shortcut to restore colors (which never worked). 

To get colors back, I usually navigate to the color correction settings pane, and choose one of the other correction alternatives. It is likely that I also cannot restore normal colors without a reboot.

**Comment by RE-Specto** [comment]
I recall observing this issue in my system too, however just tried on latest 2026070501 and the issue no longer reproduces. @paotsaq do you mind verifying on that version? It seems that it fixed another somewhat related issue #2770 so I suspect that this one's fixed as well.

**Comment by thestinger** [comment]
Not sure what ended up fixing this. There was an update to the Pixel firmware/driver files along with the new secure spawning implementation. We had a toggle for secure spawning already and no one ever said disabling it fixed this so I'm leaning towards it being the Pixel update but it's not clear. Someone still on the previous release could check.

**Comment by leoheitmannruiz** [comment]
I was able to reproduce the issue on 2026070501 and now upgraded to 2026071101 where I can reproduce it as well, on a Pixel 9a.

**Comment by thestinger** [comment]
@leoheitmannruiz Please open a new issue since most people are saying that it's fixed in the existing issues. It could be another problem.

**Comment by leoheitmannruiz** [comment]
Sure, but what do you mean by "most people"? I can only see @RE-Specto

**Comment by thestinger** [comment]
There's https://github.com/GrapheneOS/os-issue-tracker/issues/5978#issuecomment-4950880901 too and confirmations from others elsewhere.

**Comment by paotsaq** [comment]
> I recall observing this issue in my system too, however just tried on latest 2026070501 and the issue no longer reproduces. [@paotsaq](https://github.com/paotsaq) do you mind verifying on that version? It seems that it fixed another somewhat related issue [#2770](https://github.com/GrapheneOS/os-issue-tracker/issues/2770) so I suspect that this one's fixed as well.

Hello! Sorry for the late response.

Unfortunately, it is not yet fixed on my end. I'm happy to help debugging/provide logs. I'm on `2026070501`, Pixel 8 Pro. Any color correction seems to be stuck. The toggle works (and the accessibility shortcut changes the toggle, too), but there are no changes. I just rebooted the phone to ensure this was not a "stateful" thing.

**Comment by thestinger** [comment]
You're not on the latest release.

**Comment by paotsaq** [comment]
> You're not on the latest release.

I enrolled on the beta releases, installed `2026070501`, still reproducible...Should another issue be opened? It seems like the same situation still.

**Comment by thestinger** [comment]
Yes, open a new issue with a full description. These ones are remaining closed.
