### ISSUE TITLE
Stock keyboard clashes with BT keyboard

### ISSUE THREAD

**Issue by n01zec0re** [GrapheneOS/os_issue_tracker#6554]
When user has stock keyboard enabled and BT keyboard is connected, opening search bars and text input fields causes a visual glitch that covers/blocks the entire screen, making it unusable. Some apps always do it, some apps do it randomly, but it makes using a BT keyboard totally unreliable, especially in desktop mode.

Installing a different keyboard app like Openboard or Helisboard doesn't trigger this bug and is a temporary workaround, but identifies the cause is the stock keyboard.

**Steps to reproduce:**

1) Connect BT keyboard and make sure stock Graphene keyboard is enabled
2) Go to Settings > Display > Screen timeout
3) Change the setting until device asks for PIN/passphrase confirmation
4) Tap the input field to enter text

Bug is shown in the 2 videos below using Tuta Mail app and X webkit wrapper:

https://github.com/user-attachments/assets/cfe40207-cbf4-47ec-ab31-c482b2808631
https://github.com/user-attachments/assets/8af866b4-cfd1-4508-aac4-bf77c1497c9b

**Comment by thestinger** [comment]
On which OS release?

**Comment by n01zec0re** [comment]
> On which OS release?

discovered on the first experimental QPR1 release, still present on latest 2025112100

**Comment by n01zec0re** [comment]
tested on last pre-QPR1 build 2025110801 with a wired keyboard, and the bug isn't present

**Comment by justin025** [comment]
Issue has existed for a number of releases now, never bothered to open an issue because opening and closing the app drawer or control center always fixed the issue in the short term. Force stopping the aosp keyboard is the best fix ive found to this bug, the issue is resolved until the external keyboard is disconnected and reconnected. 

The solution in my opinion would be to force stop/restart the aosp keyboard automatically when an external perpetual is connected.

**Comment by n01zec0re** [comment]
this bug persists even if the stock keyboard isnt the main input method

QPR2 re-enabled stock keyboard (i had deactivated it) while still having 3rd party app as chosen input method, and the bug happens

**Comment by justin025** [comment]
Should be fixed in the release 2026062200 along with many other bugs related to desktop mode.
